# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f838989b92f097dfaab283a2012797d5383ca3f2094d40a4c8577778921ca5d4d4c7f33188572f6053bcea49e99b503c614e5991cbe519191c28d43d540ac8

test:
  secret_key_base: 02bd421c26a6fc2348e01e37ab61008f1930512a51d8daeb1863913e3e39a30f391b9a44496d04eb3d393b5d98adc55b1e92f6f986cc53219c8452c39a42cdcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
